version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16.11.1@sha256:956e4063d7e6365eac95f0894efc3fc88bb8fd36ce613469eb73b960800b6134
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install-dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run linter
          command: npm run lint
      - run:
          name: Run unit tests
          command: npm run test:unit
      - run:
          name: codecov
          command: bash <(curl -s https://codecov.io/bash)
